version: '2'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:9.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=tinyauth
    - POSTGRES_USER=tinyauth
    - POSTGRES_PASSWORD=tinyauth

  tinyauth:
    image: tinyauth/tinyauth:dev
    depends_on:
      - postgres
    command: /gunicorn.sh
    user: flask
    environment:
    - POSTGRES_USER=tinyauth
    - POSTGRES_PASSWORD=tinyauth

  httpbin:
    build: httpbin

  nginx:
    build: nginx
    depends_on:
      - tinyauth
      - httpbin
    ports:
      - "0.0.0.0:80:80"
